[versions]
assertj = "3.27.6"
junit = "5.14.1"
nmcp = "1.3.0"
spotless = "8.1.0"

[plugins]
nmcp = { id = "com.gradleup.nmcp", version.ref = "nmcp" }
nmcp-aggregation = { id = "com.gradleup.nmcp.aggregation", version.ref = "nmcp" }
spotless = { id = "com.diffplug.spotless", version.ref = "spotless" }

[libraries]
assertj-core = { module = "org.assertj:assertj-core", version.ref = "assertj" }
junit-bom = { module = "org.junit:junit-bom", version.ref = "junit" }

# versions managed by junit-bom
junit-jupiter = { module = "org.junit.jupiter:junit-jupiter"}
junit-platform-launcher = { module = "org.junit.platform:junit-platform-launcher" }
